#!/bin/bash

echo "⚙️ [configure_django.sh] Configuration du projet Django..."

PROJECT_DIR="$BASE_DIR/$SITE_NAME"
SETTINGS_DIR="$PROJECT_DIR/$SITE_NAME"
SETTINGS_PATH="$SETTINGS_DIR/settings.py"
TEMPLATE_PATH="$BASE_DIR/templates/settings.template.py"
ENV_PATH="$SETTINGS_DIR/.env"
GUNICORN_SOCKET="/run/gunicorn-$SITE_NAME.sock"

# 1. Créer le projet Django s’il n’existe pas
if [[ ! -d "$PROJECT_DIR" ]]; then
    echo "📁 Création du projet Django : $SITE_NAME"
    django-admin startproject "$SITE_NAME" "$PROJECT_DIR"
else
    echo "ℹ️ Projet Django déjà existant. Aucun changement."
fi

# 2. Installer python-dotenv
source "$PROJECT_DIR/venv/bin/activate"
pip install python-dotenv

# 3. Générer une SECRET_KEY
SECRET_KEY=$(openssl rand -base64 64 | tr -dc 'a-zA-Z0-9' | head -c50)

# 4. Générer le fichier .env
cat > "$ENV_PATH" <<EOF
# Auto-generated by configure_django.sh
DEBUG=False
SECRET_KEY=$SECRET_KEY
DOMAIN_NAME=$DOMAIN_NAME
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASS=$DB_PASS
GUNICORN_SOCKET=$GUNICORN_SOCKET
EOF

echo "✅ Fichier .env généré à $ENV_PATH"

# 5. Sauvegarde du settings.py existant
if [[ -f "$SETTINGS_PATH" ]]; then
    cp "$SETTINGS_PATH" "$SETTINGS_PATH.bak_$(date +%s)"
    echo "💾 Ancien settings.py sauvegardé."
fi

# 6. Remplir settings.py à partir du template
echo "🧩 Application du template settings.template.py..."
export DEBUG SECRET_KEY DOMAIN_NAME DB_NAME DB_USER DB_PASS GUNICORN_SOCKET SITE_NAME
envsubst < "$TEMPLATE_PATH" > "$SETTINGS_PATH"

echo "✅ Nouveau settings.py généré depuis template."

# 7. Écraser urls.py avec le template personnalisé
URLS_TEMPLATE="$BASE_DIR/templates/urls.template.py"
URLS_PATH="$SETTINGS_DIR/urls.py"

if [[ -f "$URLS_TEMPLATE" ]]; then
    cp "$URLS_TEMPLATE" "$URLS_PATH"
    echo "✅ Fichier urls.py personnalisé appliqué."
else
    echo "⚠️ Template urls.py non trouvé. Aucun changement appliqué."
fi